DROP TABLE IF EXISTS vehicles CASCADE;

CREATE TABLE vehicles  (
  vehicle_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  make varchar(255),
  model varchar(255),
  color varchar(255),
  type varchar (255),
  year integer
);

INSERT INTO vehicles  (make,model,color,type,year)
VALUES
  ('Cadillac','Deville','violet','full-size',2000),
  ('Acura','TLS','white','full-size', 2015),
  ('Toyota','Tacoma','orange','truck', 2018),
  ('Hyundai','Tucson','green','SUV', 2016),
  ('Buick','Enclave','red','SUV', 2014);
